name: flutter_instagram_project
description: A new Flutter project.



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'







dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  flutter_staggered_grid_view: ^0.6.2

  
  
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  
  
  
  
  






flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - images/
    - fonts/
  

  
  

  
  

  
  
  
  
  
  fonts:
   - family: GB
     fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700
  
   - family: GE
     fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800
  
   - family: GH
     fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900
 
   - family: GL
     fonts:
        - asset: assets/fonts/GilroyLight.ttf
  
   - family: GM
     fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500
  
   - family: GR
     fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400
          
   - family: GT
     fonts:
        - asset: assets/fonts/GilroyThin.ttf
          
   - family: SM
     fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500